### ISSUE TITLE
rPi Pico RP2040 Documentation

### ISSUE THREAD

**Issue by PeteHaughie** [sensorium/Mozzi#170] opened 2023-02-16 16:25 UTC
I realise that the RP2040 is a new addition to the supported boards but I'm finding it hard to get my head around how to go about writing sketches and circuits for the board.

Is the default the PWM pin the same? Is HIFI mode necessary and supported? Do we need an external DAC?

An example sketch and layout in an article explaining the differences would be greatly appreciated.

**Comment by PeteHaughie** [comment] 2023-02-16 17:23
I've gone back and searched through the docs and noticed that the audio output pin is set to default GP0 which is essentially A0. So for anyone needing this info:
Is the default the PWM pin the same? No
Is HIFI mode necessary and supported? No and no
Do we need an external DAC? No

**Comment by tomcombriat** [comment] 2023-02-16 21:38
Hi Pete,

The README file is up-to-date on the RP2040, with the default pin specified. The "Hardware specific notes" also tell the different modes available for this platform and how to configure. The website is always a bit behind as it is not regenerated every time something is added.
If you have some suggestions about how to enhance the documentation do not hesitate :)!

Will close this issue soon as the problem is solved.

**Comment by pschatzmann** [comment] 2023-02-28 05:35
I had a look at the Readme and was positively surprised that an external DAC is supported now as well.

**Closed** 2023-02-28 11:08 UTC
